import assert from 'node:assert/strict';
import { prisma } from './dist/server/prisma.js';
import { ensureDb, castVote, getPhase } from './dist/server/store.js';
import { requestAuthCode, verifyAuthCode, loginRegisteredUser, findAuthSessionByToken, logoutUser } from './dist/server/userAuth.js';
import { normalizeIp, networkHash, windowMs, votingRules, voteAllowance } from './dist/server/antiAbuse.js';
import { mailContent } from './dist/server/mailer.js';
if (!new URL(process.env.DATABASE_URL).pathname.endsWith('_qa')) throw new Error('Isolated QA database required');
const captured = new Map();
const deliver = async (identifier, code) => captured.set(identifier, code);
async function register(channel, identifier, ip) {
  await requestAuthCode(channel, identifier, 'register', ip, deliver);
  return verifyAuthCode(channel, identifier, captured.get(identifier), 'register', ip);
}
try {
  assert.equal(normalizeIp('::ffff:192.0.2.1'), '192.0.2.1');
  assert.equal(networkHash('::ffff:c000:201'), networkHash('192.0.2.1'));
  assert.equal(normalizeIp('2001:0db8:0:0:0:0:0:1'), '2001:db8::1');
  assert.throws(() => normalizeIp('192.0.2.1, 203.0.113.1'));
  await ensureDb();
  assert.equal(await prisma.work.count(), 0);
  const configRow = await prisma.appConfig.findUnique({where:{key:'config'}});
  const config = {...configRow.value, voteStart:new Date(Date.now()-60000).toISOString(),voteEnd:'',rules:votingRules};
  assert.equal(getPhase(config), 'active');
  assert.equal(getPhase({...config,voteStart:''}), 'pending');
  await prisma.appConfig.update({where:{key:'config'},data:{value:config}});
  await prisma.work.create({data:{id:'qa_work',code:'QA01',title:'隔离测试作品',author:'测试',themeId:'A',themeName:'测试',type:'image',cover:'/qa.png',description:'仅用于独立测试数据库',status:'published',votes:0,displayOrder:1,createdAt:new Date(),updatedAt:new Date()}});
  const ip = '192.0.2.10';
  const alice = await register('email','alice@example.test',ip);
  const bob = await register('phone','13800000001',ip);
  const carol = await register('email','carol@example.test',ip);
  const fourth = await register('phone','13800000002',ip);
  for(let i=4;i<21;i++) await register('email',`campus${i}@example.test`,ip);
  assert.equal(await prisma.user.count({where:{registrationIpHash:networkHash(ip)}}),21);
  await assert.rejects(() => verifyAuthCode('email','alice@example.test',captured.get('alice@example.test'),'register',ip), /验证码/);
  const login = await loginRegisteredUser('email','ALICE@EXAMPLE.TEST',ip);
  assert.equal(login.userId,alice.userId);
  assert.equal((await loginRegisteredUser('phone','13800000001',ip)).userId,bob.userId);
  assert.equal((await findAuthSessionByToken(login.token)).userId,alice.userId);
  await logoutUser(login.token);
  assert.equal(await findAuthSessionByToken(login.token),undefined);
  await assert.rejects(() => loginRegisteredUser('email','missing@example.test',ip), /尚未注册/);
  console.log('PASS: 21 same-IP mixed phone/email registrations succeed, first registration verification, identifier-only login, replay rejection, session logout');
  const attempts = await Promise.allSettled(Array.from({length:12},(_,i)=>castVote([alice,bob,carol][i%3].userId,'qa_work',ip)));
  assert.equal(attempts.filter(r=>r.status==='fulfilled').length,9);
  assert.equal(await prisma.voteRecord.count(),9);
  assert.equal((await prisma.work.findUnique({where:{id:'qa_work'}})).votes,9);
  assert.equal((await voteAllowance(prisma,fourth.userId,networkHash(ip))).remaining,3);
  await castVote(fourth.userId,'qa_work',ip);
  assert.equal((await voteAllowance(prisma,fourth.userId,networkHash(ip))).remaining,2);
  await assert.rejects(()=>castVote(carol.userId,'qa_work','::ffff:192.0.2.10'), /24小时/);
  const individual = await register('email','individual@example.test','192.0.2.20');
  for(let i=0;i<3;i++)await castVote(individual.userId,'qa_work','192.0.2.'+(21+i));
  await assert.rejects(()=>castVote(individual.userId,'qa_work','192.0.2.30'), /账号24小时/);
  const old = await prisma.voteRecord.findFirst({where:{userId:individual.userId}});
  await prisma.voteRecord.update({where:{id:old.id},data:{createdTime:new Date(Date.now()-windowMs-1000)}});
  await castVote(individual.userId,'qa_work','192.0.2.30');
  console.log('PASS: 12 concurrent votes across 3 same-IP accounts accept exactly 9, fourth account keeps its own allowance, account quota cannot be bypassed by changing IP, rolling 24-hour expiry');
  const bad = 'bad@example.test';
  await requestAuthCode('email',bad,'register','192.0.2.40',deliver);
  const wrong = captured.get(bad)==='000000'?'111111':'000000';
  for(let i=0;i<5;i++)await assert.rejects(()=>verifyAuthCode('email',bad,wrong,'register','192.0.2.40'));
  const challenge = await prisma.authVerification.findFirst({where:{identifier:bad},orderBy:{createdAt:'desc'}});
  assert.equal(challenge.attempts,5); assert.ok(challenge.usedAt);
  await assert.rejects(()=>verifyAuthCode('email',bad,captured.get(bad),'register','192.0.2.40'),/验证码/);
  await assert.rejects(()=>requestAuthCode('email','fail@example.test','register','192.0.2.41',async()=>{throw new Error('delivery failed');}),/发送失败/);
  assert.equal((await prisma.authVerification.findFirst({where:{identifier:'fail@example.test'}})).delivered,false);
  await prisma.user.update({where:{id:bob.userId},data:{status:'disabled'}});
  await assert.rejects(()=>loginRegisteredUser('phone','13800000001',ip),/停用/);
  await assert.rejects(()=>castVote(bob.userId,'qa_work','192.0.2.50'),/账号不可用/);
  assert.equal(await findAuthSessionByToken(bob.token),undefined);
  const copy = JSON.stringify(mailContent('123456','register'));
  assert.ok(!/未来白杨|Future Baiyang|WLBY/.test(copy));
  assert.ok(copy.includes('文创设计大赛'));
  assert.throws(()=>mailContent('<script>','register'));
  console.log('PASS: persisted wrong-code attempts, failed-delivery unusable, disabled accounts blocked, contest-only mail template');
  const burstIp='192.0.2.60';
  for(let i=0;i<60;i++) await requestAuthCode('email',`burst${i}@example.test`,'register',burstIp,deliver);
  await assert.rejects(()=>requestAuthCode('email','burst60@example.test','register',burstIp,deliver),/一分钟/);
  await prisma.authVerification.updateMany({where:{ipHash:networkHash(burstIp)},data:{createdAt:new Date(Date.now()-61000)}});
  await requestAuthCode('email','burst60@example.test','register',burstIp,deliver);
  await assert.rejects(()=>requestAuthCode('email','burst60@example.test','register',burstIp,deliver),/120秒/);
  for(let i=1;i<5;i++){
    await prisma.authVerification.updateMany({where:{identifier:'burst60@example.test'},data:{createdAt:new Date(Date.now()-121000)}});
    await requestAuthCode('email','burst60@example.test','register',burstIp,deliver);
  }
  await prisma.authVerification.updateMany({where:{identifier:'burst60@example.test'},data:{createdAt:new Date(Date.now()-121000)}});
  await assert.rejects(()=>requestAuthCode('email','burst60@example.test','register',burstIp,deliver),/24小时内验证码/);
  console.log('PASS: shared-IP 60/minute send guard recovers after one minute; identity 120-second cooldown and 5/day quota retained');
  const smsPhone='13800000091';
  const sends=await Promise.allSettled(Array.from({length:6},()=>requestAuthCode('phone',smsPhone,'register','192.0.2.91',deliver)));
  assert.equal(sends.filter(r=>r.status==='fulfilled').length,1);
  const smsRow=await prisma.authVerification.findFirst({where:{channel:'phone',identifier:smsPhone}});
  assert.equal(smsRow.codeHash.length,64);
  assert.notEqual(smsRow.codeHash,captured.get(smsPhone));
  const verifications=await Promise.allSettled(Array.from({length:6},()=>verifyAuthCode('phone',smsPhone,captured.get(smsPhone),'register','192.0.2.91')));
  assert.equal(verifications.filter(r=>r.status==='fulfilled').length,1);
  assert.equal(await prisma.user.count({where:{phone:smsPhone}}),1);
  await assert.rejects(()=>requestAuthCode('phone','13800000092','register','192.0.2.92',async()=>{throw new Error('provider rejected');}),/短信服务/);
  await assert.rejects(()=>verifyAuthCode('phone','13800000092','123456','register','192.0.2.92'),/验证码/);
  process.env.SMS_DAILY_SEND_LIMIT=String(await prisma.authVerification.count({where:{channel:'phone'}})+1);
  const budget=await Promise.allSettled(Array.from({length:4},(_,i)=>requestAuthCode('phone','1380000010'+i,'register','192.0.2.'+(100+i),deliver)));
  assert.equal(budget.filter(r=>r.status==='fulfilled').length,1);
  await requestAuthCode('email','sms-budget-does-not-block-email@example.test','register','192.0.2.110',deliver);
  console.log('PASS: concurrent SMS sends and registrations are single-use, code hashes only, rejected deliveries cannot register, atomic SMS budget leaves email available');
  console.log('ALL SECURITY TESTS PASSED');
} finally { await prisma.$disconnect(); }
